src/Entity/Seance.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeanceRepository")
 */
class Seance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Atelier", inversedBy="seances")
     * @ORM\JoinColumn(nullable=false)
     */
    private $atelier;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="seance", orphanRemoval=true)
     */
    private $messages;

    public function __construct()
    {
        $this->ateliers = new ArrayCollection();
        $this->chats = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getAtelier(): ?Atelier
    {
        return $this->atelier;
    }

    public function setAtelier(?Atelier $atelier): self
    {
        $this->atelier = $atelier;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setSeance($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getSeance() === $this) {
                $message->setSeance(null);
            }
        }

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Atelier", mappedBy="session", orphanRemoval=true)
     */
    private $ateliers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User")
     */
    private $facilitateurs;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $admin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participant", mappedBy="session", orphanRemoval=true)
     */
    private $participants;

    public function __construct()
    {
        $this->ateliers = new ArrayCollection();
        $this->facilitateurs = new ArrayCollection();
        $this->participantsInscrits = new ArrayCollection();
        $this->participantsPresents = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|Atelier[]
     */
    public function getAteliers(): Collection
    {
        return $this->ateliers;
    }

    public function addAtelier(Atelier $atelier): self
    {
        if (!$this->ateliers->contains($atelier)) {
            $this->ateliers[] = $atelier;
            $atelier->setSession($this);
        }

        return $this;
    }

    public function removeAtelier(Atelier $atelier): self
    {
        if ($this->ateliers->contains($atelier)) {
            $this->ateliers->removeElement($atelier);
            // set the owning side to null (unless already changed)
            if ($atelier->getSession() === $this) {
                $atelier->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFacilitateurs(): Collection
    {
        return $this->facilitateurs;
    }

    public function addFacilitateur(User $facilitateur): self
    {
        if (!$this->facilitateurs->contains($facilitateur)) {
            $this->facilitateurs[] = $facilitateur;
        }

        return $this;
    }

    public function removeFacilitateur(User $facilitateur): self
    {
        if ($this->facilitateurs->contains($facilitateur)) {
            $this->facilitateurs->removeElement($facilitateur);
        }

        return $this;
    }

    public function getIsValidate(): ?bool
    {
        return $this->is_validate;
    }

    public function setIsValidate(bool $is_validate): self
    {
        $this->is_validate = $is_validate;

        return $this;
    }

    public function getAdmin(): ?User
    {
        return $this->admin;
    }

    public function setAdmin(?User $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setSession($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getSession() === $this) {
                $participant->setSession(null);
            }
        }

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">

    {% if is_granted('ROLE_ADMIN') %}
        <br>
        <h4 class="text-center">Un tutoriel est en cours de developpement</h4>
        {% elseif is_granted('ROLE_FACILITATEUR') %}
        <h1 class="titre">Les sessions</h1>
        <br>
        <div class="container-fluid">
            <div class="row row-custom">
                {%for session in sessions%}
                    {%for facilitateurSession in session.facilitateurs %}
                        {% if facilitateurSession.id is same as (app.user.id) %}
                            {%if session.isValidate and session.dateFin|date('d/m/Y') >= "now"|date('d/m/Y')%}
                                <div class="card index-card">
                                    {#<div class="card-header">{{session.nom}} <br> du {{session.dateDebut|localizeddate('full', 'none')}} au {{session.dateFin|localizeddate('full', 'none')}}</div>#}
                                    <div class="card-header nameMember" style="background-color: #DA6552;">{{session.nom}} <br> du {{session.dateDebut|date('d/m/Y')}} au {{session.dateFin|date('d/m/Y')}}</div>
                                    <div class="card-body">
                                        <h4 class="card-title">
                                            {%for atelier in ateliers%}
                                                {% for seance in seances %}
                                                    {%if atelier.session.id is same as (session.id) and atelier.id is same as (seance.atelier.id)%}
                                                        {% for facilitateur in atelier.facilitateurs %}
                                                            {% if facilitateur.id is same as (app.user.id) %}
                                                                <li><a href="{{ path('atelier', {'id': atelier.id}) }}">{{atelier.nom}}</a> (le {{ seance.date|date("Y-m-d") }} de {{ seance.heureDebut|date("H:i") }} à {{ seance.heureFin|date("H:i") }})</li>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {%endif%}
                                                {% endfor %}
                                            {%endfor%}
                                        </h4>
                                        <hr>
                                    </div>
                                    <button class="btn btn-primary btn-sm" style="background-color: #DA6552;" ></button>
                                </div>
                            {%else%}
                                <div style="margin-top: 20px;">
                                    <h5 style="text-align: center;">Vous n'avez été assigné à aucune session en cours ou à venir pour le moment</h5>
                                </div>                   
                            {%endif%}
                        {% endif %}
                    {%endfor%}
                {%endfor%}
            </div>
        </div>
    </div>
    {% else %}
        <h1 class="titre animated bounceInRight">Les sessions</h1>
        <br>
        <div class="container-fluid">
            <div class="row row-custom">
            {%for session in sessions%}
                {%if session.isValidate and session.dateFin|date('d/m/Y') >= "now"|date('d/m/Y')%}
                    <div class="card index-card animated zoomIn delay-1s">
                        {#<div class="card-header">{{session.nom}} <br> du {{session.dateDebut|localizeddate('full', 'none')}} au {{session.dateFin|localizeddate('full', 'none')}}</div>#}
                        <div class="card-header nameMember" style="background-color: #DA6552;">{{session.nom}} <br> du {{session.dateDebut|date('d/m/Y')}} au {{session.dateFin|date('d/m/Y')}}</div>
                        <div class="card-body">
                            <h4 class="card-title">
                                {%for atelier in ateliers%}
                                    {%if atelier.session.id is same as (session.id)%}
                                        <li>{{atelier.nom}}</li>
                                    {%endif%}
                                {%endfor%}
                            </h4>
                            <hr>
                            <div class="text-center">
                                <a class="btn btn-primary btn-sm hvr-grow" href="/detail/session/{{session.id}}">Voir plus</a>
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary hvr-underline-reveal" data-toggle="modal" data-target="#particiption{{ session.id }}" style="background-color: #DA6552;">Participer</button>
                    </div>
                {%else%}
                <div style="margin-top: 20px;">
                    <h5 class="text-center;">Il n'y a aucune session en cours ou à venir</h5>
                </div>                   
                {%endif%}
                <div class="modal fade" id="particiption{{ session.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Formulaire de Participation</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form>
                                <div class="container">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Nom</label>
                                            <input type="text" class="form-control" name="nom" id="nomP{{ session.id }}" required="" placeholder="entrez votre nom">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Prenom</label>
                                            <input type="text" class="form-control" name="prenom" id="prenomP{{ session.id }}" required="" placeholder="entrez votre prenom">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" name="email" id="emailP{{ session.id }}" required="" placeholder="entrez votre email">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Téléphone</label>
                                            <input type="tel" class="form-control" name="tel" id="tel{{ session.id }}" required="" placeholder="06******96">
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                <button type="button" class="btn btn-primary" onclick="addParticipant({{session.id}})">Je participe</button>
                            </div>
                        </div>
                    </div>
                </div>
            {%endfor%}
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}