src/Entity/Participant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParticipantRepository")
 */
class Participant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $tel;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $session;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_present;


    public function __construct()
    {
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getIsPresent(): ?bool
    {
        return $this->is_present;
    }

    public function setIsPresent(bool $is_present): self
    {
        $this->is_present = $is_present;

        return $this;
    }

}

src/Entity/Seance.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeanceRepository")
 */
class Seance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Atelier", inversedBy="seances")
     * @ORM\JoinColumn(nullable=false)
     */
    private $atelier;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="seance", orphanRemoval=true)
     */
    private $messages;

    public function __construct()
    {
        $this->ateliers = new ArrayCollection();
        $this->chats = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getAtelier(): ?Atelier
    {
        return $this->atelier;
    }

    public function setAtelier(?Atelier $atelier): self
    {
        $this->atelier = $atelier;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setSeance($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getSeance() === $this) {
                $message->setSeance(null);
            }
        }

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Atelier", mappedBy="session", orphanRemoval=true)
     */
    private $ateliers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User")
     */
    private $facilitateurs;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $admin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participant", mappedBy="session", orphanRemoval=true)
     */
    private $participants;

    public function __construct()
    {
        $this->ateliers = new ArrayCollection();
        $this->facilitateurs = new ArrayCollection();
        $this->participantsInscrits = new ArrayCollection();
        $this->participantsPresents = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|Atelier[]
     */
    public function getAteliers(): Collection
    {
        return $this->ateliers;
    }

    public function addAtelier(Atelier $atelier): self
    {
        if (!$this->ateliers->contains($atelier)) {
            $this->ateliers[] = $atelier;
            $atelier->setSession($this);
        }

        return $this;
    }

    public function removeAtelier(Atelier $atelier): self
    {
        if ($this->ateliers->contains($atelier)) {
            $this->ateliers->removeElement($atelier);
            // set the owning side to null (unless already changed)
            if ($atelier->getSession() === $this) {
                $atelier->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFacilitateurs(): Collection
    {
        return $this->facilitateurs;
    }

    public function addFacilitateur(User $facilitateur): self
    {
        if (!$this->facilitateurs->contains($facilitateur)) {
            $this->facilitateurs[] = $facilitateur;
        }

        return $this;
    }

    public function removeFacilitateur(User $facilitateur): self
    {
        if ($this->facilitateurs->contains($facilitateur)) {
            $this->facilitateurs->removeElement($facilitateur);
        }

        return $this;
    }

    public function getIsValidate(): ?bool
    {
        return $this->is_validate;
    }

    public function setIsValidate(bool $is_validate): self
    {
        $this->is_validate = $is_validate;

        return $this;
    }

    public function getAdmin(): ?User
    {
        return $this->admin;
    }

    public function setAdmin(?User $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setSession($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getSession() === $this) {
                $participant->setSession(null);
            }
        }

        return $this;
    }
}

templates/session/recap.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{session.nom}}{% endblock %}

{% block body %}
    <div class="col-12">
        <div class="row">
            <div class="col-8">
                <h1 class="titleSession animated fadeInRight">{{session.nom}} du {{session.dateDebut|date('d/m/Y')}} au {{session.dateFin|date('d/m/Y')}}</h1>
                <br>
                {#<h3>du {{session.dateDebut|localizeddate('full', 'none')}} au {{session.dateFin|localizeddate('full', 'none')}}</h3>    #}
                <h1 class="seance">Les Séances</h1>
                <div class="col-12">
                    <div class="row">
                        {%for seance in seances%}
                            {%if seance.atelier.session.id is same as (session.id)%}
                            <div class="col-5 card detail-card-seance animated zoomIn delay-1s">
                                <h3 class="detail-seance" style="padding-right: 30px;"> le {{seance.date|date('d/m/Y')}}</h3>
                                <h5 style="min-height: 40px; margin-left: 5px;">Lieu: {{ seance.adresse }}</h5>
                                <div class="card" style="margin-bottom: 20px">
                                    <div class="card-header titre-detail-telier">{{seance.atelier.nom}} de {{seance.heureDebut|date('h:i')}} à {{seance.heureFin|date('h:i')}}</div>
                                    <div class="card-body">
                                        <p class="card-text">{{ seance.atelier.description }}</p>
                                        <hr>
                                        <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#recap{{ seance.atelier.id }}">Voir les idées</button>
                                    </div>
                                </div>
                            </div>
                            {%endif%}
                            <div class="modal fade" id="recap{{ seance.atelier.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel" style="text-align: center">Liste des idées</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="col-12">
                                            <ol>
                                                <div class="row">
                                                {% for idee in idees %}
                                                    <div class="col-4">
                                                        {% if idee.atelier.id is same as (seance.atelier.id) %}
                                                            <li>{{ idee.intitule }}</li>
                                                        {% endif %}
                                                    </div>
                                                {% endfor %}
                                                </div>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {%endfor%}
                    </div>
                </div>
            </div>
            <div class="col-4 aside" style="background-color: #DA6552;">
                {#<h3 class="titre2 animated fadeInUp delay-2s" style="color: white;">Facilitateurs</h3>#}
                {#<div class="container-fluid">#}
                    {#<div class="row row-custom">#}
                        {#{%for facilitateur in session.facilitateurs%}#}
                            {#<div class="card cardDetailSession">#}
                                {#<div class="card-body">#}
                                    {#<p class="card-title nameMemberBlack">{{facilitateur.prenom}}<br>{{facilitateur.nom}}</p>#}
                                {#</div>#}
                            {#</div>#}
                        {#{%endfor%}#}
                    {#</div>#}
                {#</div>#}
                {#<h3 class="titre2 animated fadeInUp delay-3s" style="color: white; text-align: center;">Participant</h3>#}
                {#<div class="container-fluid">#}
                    {#<div class="row row-custom">#}
                        {#{%for participant in participantSession%}#}
                            {#<div class="card cardDetailSession">#}
                                {#<div class="card-body">#}
                                    {#<p class="card-title nameMemberBlack">{{participant.prenom}}</p>#}
                                    {#<p class="card-title nameMemberBlack">{{participant.nom}}</p>#}
                                    {#<hr>#}
                                    {#{% if not participant.isPresent %}#}
                                        {#<p class="text-center" style="margin-bottom: 0px"><i class="fas fa-check fa-2x text-center" style="color: #28A745"></i></p>#}
                                    {#{% else %}#}
                                        {#<p class="text-center" style="margin-bottom: 0px"><i class="fas fa-times fa-2x text-center" style="color: red"></i></p>#}
                                    {#{% endif %}#}
                                {#</div>#}
                            {#</div>#}
                        {#{%endfor%}#}
                    {#</div>#}
                {#</div>#}
                <h3 class="titre2 animated fadeInUp delay-2s" style="color: white;">Facilitateurs</h3>
                <div id="testt" class="col-sm-12 col-md-12 col-lg-12">
                    <div id="test" class="row row-custom">
                        {%for facilitateur in session.facilitateurs%}
                            <div id="card" class="card card-fac-session col-md-12 col-lg-5">
                                <div id="col-12" class="text-center">
                                    <p class="card-title nameMemberBlack name-card-session" style="margin-top: 5px">{{facilitateur.prenom}}<br>{{facilitateur.nom}}</p><hr>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <h3 class="titre2 animated fadeInUp delay-3s" style="color: white; text-align: center;">Participants</h3>
                <div id="testt" class="col-sm-12 col-md-12 col-lg-12">
                    <div id="test" class="row row-custom">
                        {%for participant in participantSession%}
                            <div class="card card-fac-session col-sm-5 col-md-5 col-lg-5">
                                <div class="text-center">
                                    <p class="card-title nameMemberBlack">{{participant.nom}}</p>
                                    <p class="card-title nameMemberBlack">{{participant.prenom}}</p>
                                    <hr>
                                    {% if participant.isPresent %}
                                    <p class="text-center" style="margin-bottom: 0px"><i class="fas fa-check fa-2x text-center" style="color: #28A745"></i></p>
                                    {% else %}
                                    <p class="text-center" style="margin-bottom: 0px"><i class="fas fa-times fa-2x text-center" style="color: red"></i></p>
                                    {% endif %}
                                </div>
                            </div>
                        {%endfor%}
                    </div>
                </div>
                <br><br>
            </div>
        </div>
    </div>
{% endblock %}